#!/usr/bin/env python3
"""Generate a hash manifest for the main local evidence artifacts."""

from __future__ import annotations

import csv
import hashlib
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_CSV = REPO_ROOT / "results/processed/artifact_manifest.csv"

FIELDNAMES = [
    "artifact",
    "status",
    "bytes",
    "sha256",
    "producer",
    "role",
    "required_for_local_gate",
    "notes",
]


@dataclass(frozen=True)
class ArtifactSpec:
    path: str
    producer: str
    role: str
    required: bool = True
    notes: str = ""


ARTIFACTS = (
    ArtifactSpec("results/processed/replay_experiments.csv", "scripts/run_replay_experiments.py", "model and firmware-sim replay status"),
    ArtifactSpec("results/processed/replay_negative_tests.csv", "scripts/run_replay_negative_tests.py", "replay comparator positive and negative fixtures"),
    ArtifactSpec("results/processed/firmware_build.csv", "scripts/build_firmware.py", "firmware compiler/fallback build ledger"),
    ArtifactSpec("results/processed/full_rtl_replay.csv", "scripts/run_full_rtl_replay.py", "full firmware-running RTL replay status ledger"),
    ArtifactSpec("results/processed/firmware_source_comparison.csv", "scripts/run_full_rtl_replay.py", "fallback versus compiler-backed firmware source comparison ledger"),
    ArtifactSpec("results/processed/full_rtl_replay_negative.csv", "scripts/run_full_rtl_negative.py", "full RTL replay corruption-test status ledger"),
    ArtifactSpec("results/processed/runtime_overhead.csv", "scripts/run_runtime_overhead.py", "current harness runtime and overhead-blocker ledger"),
    ArtifactSpec("results/processed/runtime_overhead_summary.csv", "scripts/run_runtime_overhead.py", "runtime overhead summary and blocker status"),
    ArtifactSpec("results/processed/verilator_compile_smoke.csv", "scripts/check_verilator_compile.py", "Verilator compile/build smoke-test status", required=False, notes="generated by final CI or make verilator-smoke"),
    ArtifactSpec("results/raw/verilator/build.log", "scripts/run_full_rtl_replay.py", "sanitized Verilator harness build log"),
    ArtifactSpec("results/processed/firmware_sim_replay.csv", "scripts/rv32i_firmware_sim.py", "RV32I interpreter replay rows"),
    ArtifactSpec("results/processed/rtl_capsule_exports.csv", "scripts/export_rtl_capsules.py", "RTL-smoke capsule export and corruption checks"),
    ArtifactSpec("results/processed/rtl_capsule_event_classes.csv", "scripts/summarize_rtl_capsule_classes.py", "RTL-smoke capsule event-class counts"),
    ArtifactSpec("results/processed/rtl_firmware_alignment.csv", "scripts/check_rtl_firmware_alignment.py", "RTL-smoke versus firmware-sim alignment"),
    ArtifactSpec("results/processed/randomized_interrupt_campaign.csv", "scripts/run_randomized_interrupt_campaign.py", "seeded RTL-smoke interrupt campaign rows"),
    ArtifactSpec("results/processed/randomized_interrupt_summary.csv", "scripts/summarize_randomized_interrupt_campaign.py", "seeded interrupt campaign summary"),
    ArtifactSpec("results/processed/randomized_interrupt_coverage.csv", "scripts/summarize_randomized_interrupt_campaign.py", "seeded interrupt coverage and TODO checklist"),
    ArtifactSpec("results/processed/randomized_interrupt_corruption.csv", "scripts/summarize_randomized_interrupt_campaign.py", "seeded interrupt corruption-rejection checks"),
    ArtifactSpec("results/processed/trace_sizes.csv", "scripts/collect_trace_sizes.py", "baseline trace-size rows"),
    ArtifactSpec("results/processed/baseline_comparison.csv", "scripts/generate_conference_evidence_tables.py", "conference baseline comparison rows"),
    ArtifactSpec("results/processed/ablations.csv", "scripts/run_ablations.py", "model-level ablation rows"),
    ArtifactSpec("results/processed/event_sufficiency.csv", "scripts/run_ablations.py", "model event-sufficiency summary"),
    ArtifactSpec("results/processed/event_sufficiency_matrix.csv", "scripts/generate_conference_evidence_tables.py", "conference event-sufficiency matrix"),
    ArtifactSpec("results/processed/rtl_smoke_ablations.csv", "scripts/run_rtl_smoke_ablations.py", "RTL-smoke event-class ablations"),
    ArtifactSpec("results/processed/rtl_smoke_event_sufficiency.csv", "scripts/run_rtl_smoke_ablations.py", "RTL-smoke required event-class summary"),
    ArtifactSpec("results/processed/scaling_workloads.csv", "scripts/generate_conference_evidence_tables.py", "synthetic model scaling workload ledger"),
    ArtifactSpec("results/processed/buffer_sweep.csv", "scripts/generate_conference_evidence_tables.py", "synthetic model buffer-depth sweep"),
    ArtifactSpec("results/processed/hdl_checks.csv", "scripts/run_hdl_checks.py", "directed HDL simulation and lint rows"),
    ArtifactSpec("results/processed/standalone_self_replay_smokes.csv", "scripts/run_standalone_self_replay_smokes.py", "focused Icarus standalone self-replay matrix rows"),
    ArtifactSpec("results/processed/picorv32_smoke_summary.csv", "scripts/summarize_picorv32_smokes.py", "PicoRV32 wrapper smoke observed capsule summary"),
    ArtifactSpec("results/processed/picorv32_smoke_coverage.csv", "scripts/summarize_picorv32_smokes.py", "PicoRV32 wrapper smoke log-level coverage checks"),
    ArtifactSpec("results/processed/benchmark_coverage.csv", "scripts/summarize_benchmark_coverage.py", "per-benchmark local evidence coverage ledger"),
    ArtifactSpec("results/processed/formal_checks.csv", "scripts/run_formal_checks.py", "bounded formal check rows"),
    ArtifactSpec("results/processed/formal_coverage.csv", "scripts/summarize_formal_coverage.py", "formal coverage matrix source"),
    ArtifactSpec("results/processed/overflow_contracts.csv", "scripts/summarize_overflow_contracts.py", "bounded overflow contract evidence"),
    ArtifactSpec("results/processed/proof_obligations.csv", "scripts/summarize_proof_obligations.py", "proof-obligation source"),
    ArtifactSpec("results/processed/synthesis.csv", "scripts/parse_synthesis_reports.py", "generic synthesis status"),
    ArtifactSpec("results/processed/synthesis_overhead.csv", "scripts/summarize_synthesis_overhead.py", "generic synthesis overhead context"),
    ArtifactSpec("results/processed/second_core_breadth.csv", "scripts/run_second_core_breadth.py", "FemtoRV32 second-core wrapper lint/synthesis breadth gate"),
    ArtifactSpec("results/processed/second_core_irq_candidate.csv", "scripts/probe_second_core_irq_candidate.py", "Hazard3 interrupt-capable second-core candidate probe"),
    ArtifactSpec("results/processed/hazard3_irq_smoke.csv", "scripts/run_hazard3_irq_smoke.py", "focused Hazard3 true machine-external-interrupt firmware smoke"),
    ArtifactSpec("results/processed/hazard3_v2_replay_smoke.csv", "scripts/run_hazard3_v2_replay_smoke.py", "seeded Hazard3 v2 MMIO+IRQ ReplayCapsule replay-consumer matrix"),
    ArtifactSpec("results/processed/second_core_replay_smokes.csv", "scripts/run_second_core_replay_smokes.py", "focused FemtoRV32 capsule-derived replay smoke matrix"),
    ArtifactSpec("results/processed/second_core_v2_smokes.csv", "scripts/run_second_core_v2_smokes.py", "focused FemtoRV32 v2 MMIO replay-consumer smoke matrix"),
    ArtifactSpec("results/processed/mapped_synthesis.csv", "scripts/run_mapped_synthesis.py", "mapped synthesis status ledger"),
    ArtifactSpec("results/processed/mapped_overhead.csv", "scripts/run_mapped_synthesis.py", "mapped overhead status ledger"),
    ArtifactSpec("results/processed/mapped_recorder_presence.csv", "scripts/check_mapped_recorder_presence.py", "mapped recorder presence check"),
    ArtifactSpec("results/processed/full_core_mapped_summary.csv", "scripts/run_mapped_synthesis.py", "full-core same-target mapped summary"),
    ArtifactSpec("results/processed/workload_scaling.csv", "scripts/run_workload_scaling.py", "top-conference workload scaling ledger"),
    ArtifactSpec("results/processed/scaled_firmware_build.csv", "scripts/generate_scaled_workloads.py", "compiler-backed scaled firmware ledger"),
    ArtifactSpec("results/processed/capsule_baseline_comparison.csv", "scripts/run_capsule_baselines.py", "capsule size baseline comparison rows"),
    ArtifactSpec("results/processed/capsule_baseline_summary.csv", "scripts/run_capsule_baselines.py", "capsule size baseline medians and reductions"),
    ArtifactSpec("results/processed/buffer_sensitivity.csv", "scripts/run_buffer_sensitivity.py", "buffer depth overflow and replay availability rows"),
    ArtifactSpec("results/processed/buffer_sensitivity_summary.csv", "scripts/run_buffer_sensitivity.py", "buffer sensitivity trends by depth and workload scale"),
    ArtifactSpec("results/processed/runtime_scaling.csv", "scripts/run_runtime_scaling.py", "runtime scaling by workload length"),
    ArtifactSpec("results/processed/runtime_scaling_summary.csv", "scripts/run_runtime_scaling.py", "runtime scaling medians by workload length"),
    ArtifactSpec("results/processed/event_ablation_scaling.csv", "scripts/run_event_ablation_scaling.py", "event-class replay ablation scaling rows"),
    ArtifactSpec("results/processed/mapped_scaling.csv", "scripts/run_mapped_scaling.py", "mapped memory/buffer/config scaling rows"),
    ArtifactSpec("results/processed/mapped_scaling_overhead.csv", "scripts/run_mapped_scaling.py", "same-target mapped scaling overhead rows"),
    ArtifactSpec("results/processed/mapped_scaling_summary.csv", "scripts/run_mapped_scaling.py", "mapped scaling summary ranges"),
    ArtifactSpec("results/processed/mapped_scaling_v2.csv", "scripts/run_mapped_scaling_v2.py", "v2 mapped status rows mirrored from measured evidence when available"),
    ArtifactSpec("results/processed/mapped_scaling_v2_measured.csv", "scripts/run_v2_measured_evaluation.py", "measured v2 same-target mapped full-core rows"),
    ArtifactSpec("results/processed/mapped_scaling_overhead_v2_measured.csv", "scripts/run_v2_measured_evaluation.py", "measured v2 same-target mapped overhead rows"),
    ArtifactSpec("results/processed/mapped_recorder_presence_v2_measured.csv", "scripts/run_v2_measured_evaluation.py", "measured v2 mapped recorder-presence rows"),
    ArtifactSpec("results/processed/asic_openpdk_yosys_area.csv", "scripts/run_asic_openpdk.py", "Nangate45 synthesis-only standard-cell area rows"),
    ArtifactSpec("results/processed/asic_openpdk_yosys_area_overhead.csv", "scripts/run_asic_openpdk.py", "Nangate45 synthesis-only standard-cell area overhead rows"),
    ArtifactSpec("results/processed/asic_openpdk_summary.csv", "scripts/run_asic_openpdk.py", "ASIC/open-PDK status summary"),
    ArtifactSpec("docs/asic_openpdk_evidence.md", "scripts/run_asic_openpdk.py", "reviewer-facing ASIC/open-PDK evidence boundary"),
    ArtifactSpec("results/processed/asic_physical_tool_probe.csv", "scripts/probe_asic_physical_tools.py", "local ASIC physical-flow tool availability probe"),
    ArtifactSpec("docs/asic_physical_tool_probe.md", "scripts/probe_asic_physical_tools.py", "reviewer-facing ASIC physical-flow blocker and action checklist"),
    ArtifactSpec("scripts/materialize_nangate45_from_orfs.py", "manual/asic-openroad", "Nangate45 PDK materializer for OpenROAD Docker image"),
    ArtifactSpec("scripts/run_asic_openroad_docker.ps1", "manual/asic-openroad", "local Docker wrapper for OpenROAD ASIC evidence"),
    ArtifactSpec(".github/workflows/asic-openroad.yml", "manual/asic-openroad", "GitHub Actions OpenROAD ASIC physical-evidence workflow"),
    ArtifactSpec("results/processed/mapped_failure_diagnosis.csv", "scripts/diagnose_mapped_failures.py", "mapped P&R failure diagnosis rows"),
    ArtifactSpec("results/processed/topconf_summary.csv", "scripts/generate_topconf_tables.py", "top-conference generated summary rows"),
    ArtifactSpec("results/processed/private_marker_scan.csv", "scripts/scan_private_markers.py", "public text and artifact private-marker scan"),
    ArtifactSpec("results/processed/evaluation_metrics.csv", "scripts/summarize_evaluation_metrics.py", "headline metric rollup"),
    ArtifactSpec("results/processed/paper_build_status.csv", "scripts/build_paper.py", "paper PDF build status"),
    ArtifactSpec("results/processed/claim_audit.csv", "scripts/audit_claims.py", "claim honesty audit rows"),
    ArtifactSpec("results/processed/paper_number_audit.csv", "scripts/audit_paper_numbers.py", "paper numeric-claim audit rows"),
    ArtifactSpec("results/processed/todo_audit.csv", "scripts/audit_todos.py", "paper TODO/citation/asset audit rows"),
    ArtifactSpec("results/processed/toolchain_status.csv", "scripts/run_all_tests.py", "local tool availability and blocker ledger"),
    ArtifactSpec("results/processed/final_ci_gate_status.csv", ".github/workflows/final-reproduce.yml", "final GitHub Actions gate status", required=False, notes="generated only by final CI"),
    ArtifactSpec("results/processed/final_ci_verification.csv", "manual/final-packaging", "final GitHub Actions run, step, artifact, and package verification"),
    ArtifactSpec("docs/final_evidence_lock.md", "scripts/generate_submission_docs.py", "final locked evidence summary"),
    ArtifactSpec("docs/reviewer_attack_responses.md", "scripts/generate_submission_docs.py", "reviewer objection responses grounded in generated evidence"),
    ArtifactSpec("docs/main_track_submission_review.md", "scripts/generate_submission_docs.py", "simulated main-track reviewer panel"),
    ArtifactSpec("docs/main_track_readiness_review.md", "scripts/generate_submission_docs.py", "final main-track readiness review"),
    ArtifactSpec("paper/figures/table_event_sufficiency.md", "scripts/generate_conference_evidence_tables.py", "conference event-sufficiency table"),
    ArtifactSpec("Dockerfile", "manual/reproducibility", "container reproduction recipe"),
    ArtifactSpec(".dockerignore", "manual/reproducibility", "container context exclusions"),
    ArtifactSpec(".github/workflows/reproduce.yml", "manual/reproducibility", "GitHub Actions reproduction workflow"),
    ArtifactSpec(".devcontainer/devcontainer.json", "manual/reproducibility", "developer container configuration"),
    ArtifactSpec("docs/formal_coverage_matrix.md", "scripts/summarize_formal_coverage.py", "reviewer-facing formal coverage table"),
    ArtifactSpec("docs/proof_obligation_matrix.md", "scripts/summarize_proof_obligations.py", "reviewer-facing proof-obligation matrix"),
    ArtifactSpec("docs/second_core_breadth.md", "scripts/run_second_core_breadth.py", "reviewer-facing second-core breadth boundary"),
    ArtifactSpec("docs/second_core_irq_candidate.md", "scripts/probe_second_core_irq_candidate.py", "reviewer-facing interrupt-capable second-core candidate boundary"),
    ArtifactSpec("docs/hazard3_irq_smoke.md", "scripts/run_hazard3_irq_smoke.py", "reviewer-facing focused Hazard3 true-ISR smoke boundary"),
    ArtifactSpec("docs/hazard3_v2_replay_smoke.md", "scripts/run_hazard3_v2_replay_smoke.py", "reviewer-facing seeded Hazard3 v2 MMIO+IRQ replay matrix"),
    ArtifactSpec("docs/second_core_replay_smokes.md", "scripts/run_second_core_replay_smokes.py", "reviewer-facing focused FemtoRV32 replay-smoke matrix"),
    ArtifactSpec("docs/second_core_v2_smokes.md", "scripts/run_second_core_v2_smokes.py", "reviewer-facing focused FemtoRV32 v2 MMIO replay-consumer matrix"),
    ArtifactSpec("docs/standalone_self_replay_smokes.md", "scripts/run_standalone_self_replay_smokes.py", "reviewer-facing standalone self-replay matrix boundary"),
    ArtifactSpec("results/raw/model_suite_traces.json", "scripts/replaycapsule_model.py", "model trace bundle"),
    ArtifactSpec("results/raw/firmware_sim_traces.json", "scripts/rv32i_firmware_sim.py", "firmware-sim trace bundle"),
    ArtifactSpec("results/raw/phase12_sensor_threshold_trace.json", "scripts/replaycapsule_model.py", "model smoke trace"),
    ArtifactSpec("firmware/Makefile", "manual/firmware", "bare-metal firmware build recipe"),
    ArtifactSpec("firmware/linker.ld", "manual/firmware", "RV32I bare-metal linker script"),
    ArtifactSpec("firmware/startup.S", "manual/firmware", "minimal RV32I startup code"),
    ArtifactSpec("tb/verilator/main.cpp", "manual/rtl-harness", "Verilator harness CLI"),
    ArtifactSpec("tb/verilator/rtl_harness.cpp", "manual/rtl-harness", "firmware-running RTL record/replay harness"),
    ArtifactSpec("tb/verilator/runtime_main.cpp", "manual/runtime-overhead", "runtime-overhead Verilator harness CLI"),
    ArtifactSpec("tb/verilator/picorv32_baseline_top.sv", "manual/runtime-overhead", "no-recorder PicoRV32 runtime baseline top"),
    ArtifactSpec("tb/verilator/capsule_io.cpp", "manual/rtl-harness", "capsule/signature JSON I/O"),
    ArtifactSpec("tb/verilator/README.md", "manual/rtl-harness", "RTL harness usage and limitations"),
    ArtifactSpec("tb/system/tb_rcv2_minimal_recorder.sv", "scripts/run_hdl_checks.py", "selected v2 minimal recorder boundary-event fidelity testbench"),
    ArtifactSpec("tb/system/tb_picorv32_standalone_self_replay_smoke.sv", "scripts/run_hdl_checks.py", "focused Icarus standalone v2 self-replay shell smoke testbench"),
    ArtifactSpec("rtl/replaycapsule_v1/rcv1_capsule_replay_checker.sv", "scripts/run_hdl_checks.py", "reusable v1 168-bit capsule replay checker used by FemtoRV32 replay smokes"),
    ArtifactSpec("tb/system/tb_rcv1_capsule_replay_checker.sv", "scripts/run_hdl_checks.py", "directed HDL testbench for the v1 capsule replay checker"),
    ArtifactSpec("rtl/replaycapsule_v1/rcv1_mmio_replay_driver.sv", "scripts/run_hdl_checks.py", "scoped v1 MMIO replay driver used by FemtoRV32 replay smokes"),
    ArtifactSpec("tb/system/tb_rcv1_mmio_replay_driver.sv", "scripts/run_hdl_checks.py", "directed HDL testbench for the v1 MMIO replay driver"),
    ArtifactSpec("tb/system/tb_femtorv32_wrapper_smoke.sv", "scripts/run_hdl_checks.py", "FemtoRV32 ReplayCapsule compiler-firmware capture and capsule-derived replay smoke testbench"),
    ArtifactSpec("constraints/ecp5_board.lpf", "manual/mapped-synthesis", "board-level ECP5 IO and clock constraints"),
    ArtifactSpec("third_party/femtorv32/femtorv32_quark.v", "scripts/run_second_core_breadth.py", "vendored FemtoRV32 Quark RV32I source"),
    ArtifactSpec("third_party/femtorv32/LICENSE", "scripts/run_second_core_breadth.py", "FemtoRV32 upstream BSD-3-Clause license"),
    ArtifactSpec("third_party/femtorv32/VENDORED.md", "scripts/run_second_core_breadth.py", "FemtoRV32 vendored source pin"),
    ArtifactSpec("third_party/hazard3/hdl/hazard3_cpu_1port.v", "scripts/probe_second_core_irq_candidate.py", "vendored Hazard3 single-port CPU top"),
    ArtifactSpec("third_party/hazard3/hdl/hazard3_core.v", "scripts/probe_second_core_irq_candidate.py", "vendored Hazard3 core implementation"),
    ArtifactSpec("third_party/hazard3/hdl/hazard3_irq_ctrl.v", "scripts/probe_second_core_irq_candidate.py", "vendored Hazard3 external IRQ controller"),
    ArtifactSpec("third_party/hazard3/LICENSE", "scripts/probe_second_core_irq_candidate.py", "Hazard3 upstream Apache-2.0 license"),
    ArtifactSpec("third_party/hazard3/VENDORED.md", "scripts/probe_second_core_irq_candidate.py", "Hazard3 vendored source pin"),
    ArtifactSpec("scripts/probe_second_core_irq_candidate.py", "manual/second-core-irq-candidate", "Hazard3 interrupt-capable second-core candidate probe"),
    ArtifactSpec("scripts/run_hazard3_irq_smoke.py", "manual/hazard3-irq-smoke", "focused Hazard3 true-ISR smoke runner"),
    ArtifactSpec("scripts/run_hazard3_v2_replay_smoke.py", "manual/hazard3-v2-replay-smoke", "seeded Hazard3 v2 MMIO+IRQ replay matrix runner"),
    ArtifactSpec("firmware/hazard3_irq_smoke/hazard3_irq_smoke.S", "scripts/run_hazard3_irq_smoke.py", "Hazard3 RV32I+Zicsr true-ISR smoke firmware"),
    ArtifactSpec("firmware/hazard3_irq_smoke/linker.ld", "scripts/run_hazard3_irq_smoke.py", "Hazard3 true-ISR smoke linker script"),
    ArtifactSpec("firmware/hazard3_replay_smoke/hazard3_replay_smoke.S", "scripts/run_hazard3_v2_replay_smoke.py", "Hazard3 v2 replay matrix RV32I+Zicsr firmware"),
    ArtifactSpec("firmware/hazard3_replay_smoke/linker.ld", "scripts/run_hazard3_v2_replay_smoke.py", "Hazard3 v2 replay matrix linker script"),
    ArtifactSpec("tb/system/tb_hazard3_irq_smoke.v", "scripts/run_hazard3_irq_smoke.py", "focused Hazard3 AHB/MMIO/IRQ true-ISR smoke testbench"),
    ArtifactSpec("tb/system/tb_hazard3_v2_replay_smoke.sv", "scripts/run_hazard3_v2_replay_smoke.py", "seeded Hazard3 v2 ReplayCapsule MMIO+IRQ replay testbench"),
    ArtifactSpec("rtl/rv32i_integration/hazard3_replaycapsule_v2_wrapper.sv", "scripts/run_hazard3_v2_replay_smoke.py", "Hazard3 ReplayCapsule v2 matrix wrapper"),
    ArtifactSpec("rtl/rv32i_integration/femtorv32_replaycapsule_wrapper.sv", "scripts/run_second_core_breadth.py", "FemtoRV32 ReplayCapsule wrapper lint/synthesis source"),
    ArtifactSpec("rtl/rv32i_integration/femtorv32_replaycapsule_v2_wrapper.sv", "scripts/run_hdl_checks.py", "scoped FemtoRV32 v2 ReplayCapsule MMIO replay-consumer wrapper"),
    ArtifactSpec("tb/system/tb_femtorv32_v2_replay_smoke.sv", "scripts/run_hdl_checks.py", "scoped FemtoRV32 v2 MMIO replay-consumer smoke testbench"),
    ArtifactSpec("scripts/run_second_core_v2_smokes.py", "manual/second-core-v2", "focused FemtoRV32 v2 MMIO replay-consumer smoke matrix runner"),
    ArtifactSpec("rtl/rv32i_integration/replaycapsule_v2_self_replay_top.sv", "scripts/run_hdl_checks.py", "reusable v2 self-replay RTL shell with source/controller integration"),
    ArtifactSpec("rtl/rv32i_integration/replaycapsule_v2_self_replay_soc.sv", "scripts/run_hdl_checks.py", "reusable v2 self-replay SoC shell with internal instruction-memory/MMIO/IRQ model"),
)

GLOBS = (
    ("paper/figures/table*.md", "scripts/render_paper_tables.py", "generated paper table source"),
    ("paper/figures/fig_*.pdf", "scripts/generate_topconf_figures.py", "top-conference generated PDF figure"),
    ("paper/tables/table_*.tex", "scripts/generate_topconf_tables.py", "top-conference generated LaTeX table"),
    ("paper/figures/*.svg", "scripts/make_figures.py", "paper SVG figure mirror"),
    ("results/figures/*.svg", "scripts/make_figures.py", "generated SVG figure source"),
    ("results/raw/tb_*_*.txt", "scripts/run_hdl_checks.py", "raw HDL compile/simulation log"),
    ("results/raw/standalone_self_replay_smokes/*.txt", "scripts/run_standalone_self_replay_smokes.py", "raw focused standalone self-replay log"),
    ("results/raw/second_core_irq_candidate/*.txt", "scripts/probe_second_core_irq_candidate.py", "raw Hazard3 interrupt-capable candidate probe log"),
    ("results/raw/hazard3_irq_smoke/*.txt", "scripts/run_hazard3_irq_smoke.py", "raw focused Hazard3 true-ISR smoke build/run log"),
    ("results/raw/hazard3_v2_replay_smoke/*.txt", "scripts/run_hazard3_v2_replay_smoke.py", "raw seeded Hazard3 v2 replay matrix build/run log"),
    ("results/raw/second_core_replay_smokes/*.txt", "scripts/run_second_core_replay_smokes.py", "raw focused FemtoRV32 replay-smoke log"),
    ("results/raw/second_core_v2_smokes/*.txt", "scripts/run_second_core_v2_smokes.py", "raw focused FemtoRV32 v2 replay-consumer smoke log"),
    ("results/raw/verilator_lint_*.txt", "scripts/run_hdl_checks.py", "raw Verilator lint log"),
    ("results/raw/formal_*.txt", "scripts/run_formal_checks.py", "raw bounded formal log"),
    ("results/raw/randomized_interrupt_campaign/*.txt", "scripts/run_randomized_interrupt_campaign.py", "raw seeded interrupt campaign log"),
    ("results/raw/rtl_capsules/*.json", "scripts/export_rtl_capsules.py", "raw exported RTL-smoke capsule"),
    ("results/raw/runtime_overhead/*.json", "scripts/run_runtime_overhead.py", "raw runtime-overhead record capsule or signature"),
    ("results/debug/pass4/*", "scripts/run_full_rtl_replay.py", "pass-4 full RTL debug event diff or trace"),
    ("results/debug/pass5_before/*", "manual/freeze", "pass-5 frozen readiness evidence"),
    ("results/debug/pass6_before/*", "manual/freeze", "pass-6 frozen readiness evidence"),
    ("results/debug/pass7_before/*", "manual/freeze", "pass-7 frozen CI evidence before overhead/mapping work"),
    ("results/debug/final_submission_lock/**/*", "scripts/generate_submission_docs.py", "final submission evidence lock copy"),
    ("results/raw/yosys_*.txt", "scripts/synth_yosys.py", "raw generic synthesis report"),
    ("results/raw/mapped_synthesis/*.txt", "scripts/run_mapped_synthesis.py", "raw mapped synthesis/place-and-route report"),
    ("results/raw/mapped_synthesis/*.json", "scripts/run_mapped_synthesis.py", "raw mapped synthesis JSON netlist"),
    ("results/raw/mapped_synthesis/*.config", "scripts/run_mapped_synthesis.py", "raw mapped ECP5 configuration text"),
    ("results/raw/mapped_synthesis/*.asc", "scripts/run_mapped_synthesis.py", "raw mapped iCE40 ASCII bitstream"),
    ("results/raw/mapped_scaling_v2_measured/*.txt", "scripts/run_v2_measured_evaluation.py", "raw measured v2 mapped synthesis/place-and-route report"),
    ("results/raw/mapped_scaling_v2_measured/*.json", "scripts/run_v2_measured_evaluation.py", "raw measured v2 mapped synthesis JSON netlist"),
    ("results/raw/mapped_scaling_v2_measured/*.config", "scripts/run_v2_measured_evaluation.py", "raw measured v2 mapped ECP5 configuration text"),
    ("results/raw/asic_openpdk/*_yosys_area.txt", "scripts/run_asic_openpdk.py", "raw Nangate45 synthesis-only area log"),
    ("results/raw/asic_openpdk/*_yosys_area_mapped.v", "scripts/run_asic_openpdk.py", "raw Nangate45 area-only mapped netlist"),
)


def main() -> int:
    rows: list[dict[str, str]] = []
    seen: set[Path] = set()
    for spec in ARTIFACTS:
        path = REPO_ROOT / spec.path
        rows.append(_row(path, spec.producer, spec.role, spec.required, spec.notes))
        seen.add(path)
    for pattern, producer, role in GLOBS:
        for path in sorted(REPO_ROOT.glob(pattern)):
            if path.is_dir():
                continue
            if path in seen or path == OUT_CSV:
                continue
            rows.append(_row(path, producer, role, True, "discovered by manifest glob"))
            seen.add(path)

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDNAMES)
        writer.writeheader()
        writer.writerows(rows)

    missing = [row["artifact"] for row in rows if row["required_for_local_gate"] == "yes" and row["status"] == "MISSING"]
    print(f"WROTE {_rel(OUT_CSV)}; present={len(rows) - len(missing)} missing={len(missing)}")
    if missing:
        for artifact in missing:
            print(f"MISSING {artifact}")
        return 1
    return 0


def _row(path: Path, producer: str, role: str, required: bool, notes: str) -> dict[str, str]:
    if not path.exists():
        return {
            "artifact": _rel(path),
            "status": "MISSING",
            "bytes": "NA",
            "sha256": "NA",
            "producer": producer,
            "role": role,
            "required_for_local_gate": "yes" if required else "no",
            "notes": notes,
        }
    data = path.read_bytes()
    return {
        "artifact": _rel(path),
        "status": "PRESENT",
        "bytes": str(len(data)),
        "sha256": hashlib.sha256(data).hexdigest(),
        "producer": producer,
        "role": role,
        "required_for_local_gate": "yes" if required else "no",
        "notes": notes,
    }


def _rel(path: Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()


if __name__ == "__main__":
    raise SystemExit(main())
